version: '3.8'

services:
  svm_service:
    image: svm-service 
    ports:
      - "5000:5000"
    networks:
      - app-network

  vgg19_service:
    image: vgg_service 
    ports:
      - "5001:5001"
    networks:
      - app-network
  
  frontend:
    image: my-app 
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver:bridge