# FROM python:3.9-slim
# WORKDIR /app
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt
# COPY . .
# # RUN mkdir -p static/uploads
# EXPOSE 5002
# # ENV FLASK_APP=app.py
# # ENV FLASK_RUN_HOST=0.0.0.0
# CMD ["python", "app2.py"]

#######################################################
# Use a lightweight base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application files
COPY . .
EXPOSE 5003
CMD ["python", "app2.py"]
